# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!
 inhibit_all_warnings!

target 'Book' do
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'FMDB'
    pod 'Masonry'
    pod 'Toast'
    pod 'MBProgressHUD'
    pod 'SDWebImage'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'SnapKit'
end


