# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
#pod以动态库的形式引入
use_frameworks!


target 'FrameworkDemo' do
pod 'AFNetworking'
pod 'MJRefresh'
pod 'HysteriaPlayer'
pod 'TMCache'
pod 'FMDB'
pod 'Masonry'
pod 'Toast'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'BlocksKit'
end

target 'FrameworkDemoTests' do

end

target 'FrameworkDemoUITests' do

end

